### ISSUE TITLE
Why php 7?

### ISSUE THREAD

**Issue by galtzur** [MasterRO94/searchable#1]
I wanted to use this on my laravel 5.2 project, but i saw that you require php 7.

i saw no reason for that.

**Comment by MasterRO94** [comment]
I used return type declaration and "??" operator that's why PHP7. You can update/upgrade your php version to 7 to achieve compatibility  with the package and increase the performance.

**Comment by MasterRO94** [comment]
I just have added PHP5 support. Use branch php5 for that. If there are any problems I will be waiting for new issues.
